### ISSUE TITLE
Using bootstrap columns

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-vickyantre#3]
Bootsrap has a powerfull grid system, which alows to place your elements in many ways without writing additional css code. It also has columns which allows you to define look of your website - http://getbootstrap.com/css/#grid-options.

I see you wrote your own column class:
```css
.footer .row .colomn {
    display: table-cell;
    width: 1%;
    padding: 0 20px;
    text-align: center;
    vertical-align: top;
}
```

Why you haven't used bootsrap column classes (e.g. `.col-md-1..12`) ?
Can I help you with this somehow ?
